### ISSUE TITLE
Is it possible to honor a set_dont_use   list of cells

### ISSUE THREAD

**Issue by ravi-varadarajan** [daeyeon22/artificial_netlist_generator#5]
Hi Daeyeon

Is it possible to exclude certain cells from the lef file with a set_dont_use  cell list (link in OpenROAD).  Currently it picks up ICG cells as sequential (because of the USE CLOCK construct on the clk pin). I would like avoid using ICG cells and other cells such has high drive cells etc.  I believe it will be useful option

**Comment by daeyeon22** [comment]
I’ll check ‘set_dont_use’ property in OpenDB and update in future version.

보낸 사람: ***@***.***>
보낸 날짜: 2023년 3월 8일 수요일 오전 9:04
받는 사람: ***@***.***>
참조: ***@***.***>
제목: [daeyeon22/artificial_netlist_generator] Is it possible to honor a set_dont_use list of cells (Issue #5)


Hi Daeyeon

Is it possible to exclude certain cells from the lef file with a set_dont_use cell list (link in OpenROAD). Currently it picks up ICG cells as sequential (because of the USE CLOCK construct on the clk pin). I would like avoid using ICG cells and other cells such has high drive cells etc. I believe it will be useful option

**Comment by daeyeon22** [comment]
I’ve uploaded new version you asked me.
Please check the modified test cases.

There are several modifications in tcl usage.

Windows용 메일<https://go.microsoft.com/fwlink/?LinkId=550986>에서 발송된 메일입니다.

보낸 사람: ***@***.***>
보낸 날짜: 2023년 3월 8일 수요일 오전 9:04
받는 사람: ***@***.***>
참조: ***@***.***>
제목: [daeyeon22/artificial_netlist_generator] Is it possible to honor a set_dont_use list of cells (Issue #5)


Hi Daeyeon

Is it possible to exclude certain cells from the lef file with a set_dont_use cell list (link in OpenROAD). Currently it picks up ICG cells as sequential (because of the USE CLOCK construct on the clk pin). I would like avoid using ICG cells and other cells such has high drive cells etc. I believe it will be useful option

**Comment by ravi-varadarajan** [comment]
Thanks Daeyeon

I saw the updates to the repo and updated flow.  I was able to use to generate a sweep of netlist
The dont use functionality is working fine so I  will close this issue

One enhancement request for the dont use is to take a wild char  in the cell name to match all cells with the pattern. OpenROAD and most other implementation tools allow that use mode.

I also like the updates to the README
thanks
